Repository vanvalenlab/deepcell-tracking, pull requests merged in 2021-08, with the labels that each got.

#67 Change `isbi_utils` from writing files to comparing in memory
  deepcell_tracking/isbi_utils.py
  deepcell_tracking/isbi_utils_test.py
  setup.py
Labels: enhancement, fix

#69 Bump version to 0.4.4
  setup.py
Labels: Chore

#70 `is_valid_lineage` should check if the daughter ID is valid.
  deepcell_tracking/utils.py
  deepcell_tracking/utils_test.py
  setup.py
Labels: fix
